# ----------------------- #
#      Main Configs       #
# ----------------------- #


baseurl: https://pse-libreas.github.io
url: https://pse-libreas.github.io
title: LIBREAS. Library Ideas
subtitle: Elektronische Zeitschrift für Bibliotheks- und Informationswissenschaft 
author: LIBREAS. Library Ideas
simple_search: http://google.com/search
description:
repository: PSE-LIBREAS/PSE-LIBREAS.github.io


# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: redaktion@libreas.eu

# Build settings
markdown: kramdown
#theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll/scholar
  - jekyll-sitemap
  
scholar:
  style: modern-language-association
  locale: de 	#Defines what language to use when formatting your references (this typically applies to localized terms, e.g., 'Eds.' for editors in English).
  source: ./_bibliography 	# Indicates where your bibliographies are stored.
  bibliography: references.bib 	#Indicates the name of your default bibliography. For best results, please ensure that your bibliography is encoded as ASCII or UTF-8. A string that contains a * will be passed to Dir::glob, so **/*.bib{,tex} will find all files named *.bib and *.bibtex under source.
  bibliography_template: bib
  sort_by: 	author 	#Specifies if and how bibliography entries are sorted. Entries can be sorted on multiple fields, by using a list of keys, e.g. year,month. Ordering can be specified per sort level, e.g. order: descending,ascending will sort the years descending, but per year the months are ascending. If there are more sort keys than order directives, the last order entry is used for the remaining keys.
  order: 	descending 	#Specifies order bibliography entries are sorted in. Can be ascending or descending. Ordering can be specified per sort level, e.g. descending,ascending will sort in descending on the first key then ascending order on the second key. If there are more sort keys than order directives, the last order entry is used for the remaining keys.
  group_by: year,type 	#Specifies how bibliography items are grouped. Grouping can be multi-level, e.g. type, year groups entries per publication type, and within those groups per year.
  group_order: 	descending 	#Ordering for groups is specified in the same way as the sort order. Publication types -- specified with group key type, can be ordered by adding type_order to the configuration. For example, type_order: [article,techreport] lists journal articles before technical reports. Types not mentioned in type_order are considered smaller than types that are mentioned. Types can be merge in one group using the type_aliases setting. By default phdthesis and mastersthesis are grouped as thesis. By using, for example, type_aliases: { inproceedings: article}, journal and conference articles appear in a single group. The display names for entry types are specified with type_names. Names for common types are provided, but they can be extended or overridden. For example, the default name for article is Journal Articles, but it can be changed to Papers using type_names: { article: Papers }.
  bibtex_filters: 	
    - latex
    - htmllinks

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
